### ISSUE TITLE
features to be implemented

### ISSUE THREAD

**Issue by rajat-mehra05** [jatiinyadav/Books-Library-using-ReactJs#29]
- I want to style the UI of card.
- Search Input and search button can be enhanced to look better.
- Add animation to book-cards after the search is completed.
- add genre of each book in card.

Please review this issue.

**Comment by Shubh-2402** [comment]
hii.. @rajat-mehra05  i would love to get assigned to this issue

**Comment by jatiinyadav** [comment]
> * I want to style the UI of card.
> * Search Input and search button can be enhanced to look better.
> * Add animation to book-cards after the search is completed.
> * add genre of each book in card.
> 
> Please review this issue.

You can start your work.
All the best 👍🏻.

**Comment by rajat-mehra05** [comment]
Can I create multiple PR so that the features suggested by me don't get messed up ?
