### ISSUE TITLE
Separate the book component and better loading indicator

### ISSUE THREAD

**Issue by SankalpaFernando** [jatiinyadav/Books-Library-using-ReactJs#35]
**Is your feature request related to a problem? Please describe.**
----
- The book component is in the same file as the books(parent component). It would be harder to make changes to the book component because both parent logic and child logic are in the same file.
- There is only a text which indicates the data loading, which makes a bad User experience.

**Describe the solution you'd like**
----

- Export the code for the book component rendering into a separate component file.
- Instead of loading text, add the loading indication cards for better UX

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **original screenshot**  | <b>updated screenshot </b> |

**Comment by SankalpaFernando** [comment]
Please assign this to me. I would like to contribute to the project

**Comment by jatiinyadav** [comment]
> Please assign this to me. I would like to contribute to the project



> ## **Is your feature request related to a problem? Please describe.**
> * The book component is in the same file as the books(parent component). It would be harder to make changes to the book component because both parent logic and child logic are in the same file.
> * There is only a text which indicates the data loading, which makes a bad User experience.
> 
> ## **Describe the solution you'd like**
> * Export the code for the book component rendering into a separate component file.
> * Instead of loading text, add the loading indication cards for better UX
> 
> ## Screenshots
> Original	Updated
> **original screenshot**	updated screenshot

Sounds Great, You can start your work.
All the best 👍🏻 .
