### ISSUE TITLE
Want to change the background of the books

### ISSUE THREAD

**Issue by Ash-ishJ** [jatiinyadav/Books-Library-using-ReactJs#4]
The background color of the books in home page is not looking very good.

I want to change the background of the books to a light color with little bit of transparency

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 **![image](https://user-images.githubusercontent.com/86077008/134657309-c6b91bcd-5085-400f-a956-501f3c9a1a2d.png)**  | <b>![image](https://user-images.githubusercontent.com/86077008/134657218-a2d4ec8b-54e7-43e9-b546-b232880945d0.png) </b> |

**Comment by jatiinyadav** [comment]
Thank you so much for contributing,
Don't create Issue/PR for very minor changes.

**Comment by Ash-ishJ** [comment]
I guess it was not a minor change at all. This website has books all over the front page. And the changes I requested, will make the whole UI of the front page look more professional.
