### ISSUE TITLE
Added Hover Effect on Cards, Background color modified.

### ISSUE THREAD

**Issue by shreya0204** [jatiinyadav/Books-Library-using-ReactJs#5]
I have added a hover zoom-in effect in cards to make them more user-friendly and engaging.

I have done the following changes : 
- modified background color of cards.
- added zoom in hover effects.

# Why I have modified the background.

The grey background is reflecting a drab image of the cards making it less user-pleasant UI. I have altered the hue to a brighter side making it appear beautiful and appealing.

# Screenshot

Card's background was like this.

![image](https://user-images.githubusercontent.com/78657883/134717934-62bda0ab-94da-4394-a61a-16f4c0cdd99d.png)

I have done these changes

https://user-images.githubusercontent.com/78657883/134718374-4db017c1-6c0b-4999-99a3-8cd735d36632.MP4

I hope you like the changes. If you have suggestions do let me know :)

**Comment by jatiinyadav** [comment]
Thankyou so much for contributing,

**Comment by jatiinyadav** [comment]
Thank you so much for contributing,
Change the background color of the card it is looking too white.

**Comment by shreya0204** [comment]
Okay, I got it.

How is it now

![image](https://user-images.githubusercontent.com/78657883/134778720-67922f83-e4e1-4b1d-8d9d-348200c25520.png)

**Comment by jatiinyadav** [comment]
@shreya0204 Better 👍🏻.
